/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.test.runners.codegen;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.test.generators.GenerateCompilerTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
public class TieredBackendJvmLightTreeTestGenerated extends AbstractTieredBackendJvmLightTreeTest {
  @Nested
  @TestMetadata("compiler/testData/diagnostics/testsWithStdlib")
  @TestDataPath("$PROJECT_ROOT")
  public class TestsWithStdlib {
    @Nested
    @TestMetadata("compiler/testData/diagnostics/testsWithStdlib/tieredFailures")
    @TestDataPath("$PROJECT_ROOT")
    public class TieredFailures {
      @Nested
      @TestMetadata("compiler/testData/diagnostics/testsWithStdlib/tieredFailures/fail")
      @TestDataPath("$PROJECT_ROOT")
      public class Fail {
        @Test
        @TestMetadata("isFir2IrButBackendFails.kt")
        public void testIsFir2IrButBackendFails() {
          runTest("compiler/testData/diagnostics/testsWithStdlib/tieredFailures/fail/isFir2IrButBackendFails.kt");
        }
      }

      @Nested
      @TestMetadata("compiler/testData/diagnostics/testsWithStdlib/tieredFailures/good")
      @TestDataPath("$PROJECT_ROOT")
      public class Good {
        @Test
        @TestMetadata("isKlibButBackendFails.kt")
        public void testIsKlibButBackendFails() {
          runTest("compiler/testData/diagnostics/testsWithStdlib/tieredFailures/good/isKlibButBackendFails.kt");
        }

        @Test
        @TestMetadata("isKlibButLimitedToKlib.kt")
        public void testIsKlibButLimitedToKlib() {
          runTest("compiler/testData/diagnostics/testsWithStdlib/tieredFailures/good/isKlibButLimitedToKlib.kt");
        }
      }
    }
  }
}
